# docta/mercadolibre
# @copyright 2018 Lucas Banegas
# @license MIT

build:
  nodes:
    analysis:
      tests:
        override:
        - php-scrutinizer-run

filter:
  excluded_paths: ["./tests"]

tools:
  external_code_coverage: true
  php_analyzer: true
  php_code_coverage: false
  php_code_sniffer:
    config:
      standard: PSR2
    filter:
      paths: ["./src"]
  php_cpd:
    enabled: true
    excluded_dirs: ["./tests", "./vendor"]
  php_loc:
    enabled: true
    excluded_dirs: ["./tests", "./vendor"]
