# docta/mercadolibre
# @copyright 2018 Lucas Banegas
# @license MIT

language: php

matrix:
  include:
  - php: 5.6
  - php: 7
  - php: 7.1
  - php: 7.2
  - php: nightly
  - php: hhvm-3.6
    sudo: required
    dist: trusty
    group: edge
  - php: hhvm-3.9
    sudo: required
    dist: trusty
    group: edge
  - php: hhvm-3.12
    sudo: required
    dist: trusty
    group: edge
  - php: hhvm-3.15
    sudo: required
    dist: trusty
    group: edge
  - php: hhvm-nightly
    sudo: required
    dist: trusty
    group: edge
  fast_finish: true
  allow_failures:
  - php: nightly
  - php: hhvm-nightly


before_install:
- travis_retry composer self-update

install:
- travis_retry composer require --no-interaction --prefer-source --dev scrutinizer/ocular
- travis_retry composer install --no-interaction --prefer-source

script:
- composer test-travis

after_success:
- travis_retry php ./vendor/bin/ocular code-coverage:upload --format=php-clover ./build/logs/clover.xml
